import type { GlossaryEntry } from "./glossary-types";

export const FUENTES_ENTRIES: GlossaryEntry[] = [
  {
    id: "fuente-puntual",
    name: "Fuente puntual",
    group: "fuentes",
    what: "Objeto compacto (estrella, quasar) que en la imagen es un pico, no una mancha extendida.",
    inApp: "Se marca con un punto. Al hacer clic, sus números van a Selección.",
    where: "Visor y Inspector → Selección",
  },
  {
    id: "deteccion",
    name: "Detección de fuentes",
    group: "fuentes",
    what: "Búsqueda automática de picos sobre el fondo de la imagen.",
    inApp: "Corre con los parámetros de Fuentes y dibuja marcas sobre el FITS.",
    where: "Inspector → Fuentes",
  },
  {
    id: "fwhm",
    name: "FWHM",
    group: "fuentes",
    what: "Ancho a media altura del núcleo estelar, en píxeles.",
    inApp:
      "Valores más altos buscan estrellas más gordas o una imagen poco nítida.",
    where: "Inspector → Fuentes",
  },
  {
    id: "sigma",
    name: "Sigma",
    group: "fuentes",
    what: "Umbral de detección en RMS del fondo.",
    inApp:
      "Más alto exige picos más contrastados y suele devolver menos marcas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "snr",
    name: "SNR",
    group: "fuentes",
    what: "Relación señal / ruido del pico.",
    inApp:
      "El SNR mínimo descarta picos débiles. En Selección ves el SNR de la marca.",
    where: "Inspector → Fuentes y Selección",
  },
  {
    id: "score",
    name: "Score",
    group: "fuentes",
    what: "Puntuación de relevancia (0 a 1) que mezcla aspecto visual y forma.",
    inApp: "Filtra candidatos poco convincentes y ordena el ranking.",
    where: "Inspector → Fuentes y Selección",
  },
  {
    id: "min-distance",
    name: "Distancia mínima",
    group: "fuentes",
    what: "Separación mínima entre picos, en píxeles.",
    inApp: "Evita marcar dos veces la misma estrella.",
    where: "Inspector → Fuentes",
  },
  {
    id: "max-sources",
    name: "Máximo de fuentes",
    group: "fuentes",
    what: "Tope de fuentes a devolver, ordenadas por relevancia.",
    inApp: "0 significa sin límite. Baja el número si hay demasiadas marcas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-weight",
    name: "Peso visual",
    group: "fuentes",
    what: "Cuánto pesa el aspecto visual frente a la morfología en el score.",
    inApp: "0 = solo forma; 1 = solo cómo se ve el parche.",
    where: "Inspector → Fuentes",
  },
  {
    id: "preset-deteccion",
    name: "Preset de detección",
    group: "fuentes",
    what: "Conjunto de umbrales con un nombre de situación (equilibrio, mucho ruido, baja resolución…).",
    inApp: "Rellena Fuentes. Si tocás un número, pasa a Personalizado.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-area-radius",
    name: "Radio visual",
    group: "fuentes",
    what: "Radio en píxeles del parche alrededor del pico para medir área, flujo y pico aparentes.",
    inApp: "Más radio mira un entorno más grande; demasiado agarra vecinos.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-area-sigma",
    name: "Sigma visual",
    group: "fuentes",
    what: "Umbral local del parche visual, en RMS del fondo.",
    inApp: "Define qué píxeles cuentan como parte de la fuente en ese parche.",
    where: "Inspector → Fuentes",
  },
  {
    id: "rank",
    name: "Rank",
    group: "fuentes",
    what: "Orden de relevancia entre las fuentes detectadas. 1 es la más relevante.",
    inApp: "Aparece en Selección al hacer clic en una marca.",
    where: "Inspector → Selección",
  },
  {
    id: "centroide",
    name: "Centroide",
    group: "fuentes",
    what: "Posición del pico en píxeles (X, Y) sobre el HDU.",
    inApp:
      "X e Y en Selección. No son RA/Dec salvo que haya WCS (aún no se muestran ahí).",
    where: "Inspector → Selección",
  },
  {
    id: "peak",
    name: "Peak",
    group: "fuentes",
    what: "Valor de píxel en el máximo del pico.",
    inApp: "En Selección, si el detector lo calculó.",
    where: "Inspector → Selección",
  },
  {
    id: "flux",
    name: "Flux",
    group: "fuentes",
    what: "Flujo estimado de la fuente puntual (cuentas o unidad del HDU).",
    inApp: "En Selección, si el detector lo calculó.",
    where: "Inspector → Selección",
  },
  {
    id: "mean",
    name: "Media",
    group: "fuentes",
    what: "Valor medio de píxel dentro de la región detectada.",
    inApp: "En Selección, si el detector lo calculó.",
    where: "Inspector → Selección",
  },
  {
    id: "gaia",
    name: "Cruce con Gaia",
    group: "fuentes",
    what: "Comparación de las detecciones con el catálogo Gaia.",
    inApp:
      "El botón de Fuentes pide el cruce. Selección muestra la contraparte de la marca elegida, si existe.",
    where: "Inspector → Fuentes y Selección",
  },
  {
    id: "fuente-extendida",
    name: "Fuente extendida",
    group: "fuentes",
    what: "Región no puntual de la imagen: luz difusa con forma, como una nebulosa o una galaxia.",
    inApp:
      "Se marca con un recuadro sobre la imagen y cuenta como 'extendida' en el resumen.",
    where: "Visor (recuadro) e Inspector → Selección",
  },
  {
    id: "area",
    name: "Área",
    group: "fuentes",
    what: "Cantidad de píxeles que ocupa la región extendida detectada.",
    inApp: "Aparece en Selección al marcar una fuente extendida.",
    where: "Inspector → Selección",
  },
  {
    id: "ancho-alto",
    name: "Ancho y alto",
    group: "fuentes",
    what: "Extensión horizontal y vertical, en píxeles, del recuadro que envuelve la región.",
    inApp: "Se muestran en Selección al marcar una fuente extendida.",
    where: "Inspector → Selección",
  },
  {
    id: "ext-sigma",
    name: "Sigma (extendidas)",
    group: "fuentes",
    what: "Umbral en RMS del fondo para abrir regiones de luz difusa.",
    inApp:
      "Más alto exige nebulosas más contrastadas. Lo edita el grupo Fuentes extendidas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-smooth-sigma",
    name: "Suavizado",
    group: "fuentes",
    what: "Suavizado gaussiano previo al umbral para dominar el ruido.",
    inApp:
      "Muy bajo deja ruido que abre regiones falsas; muy alto funde estructuras finas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-binning",
    name: "Factor de bin",
    group: "fuentes",
    what: "Agrupado de píxeles que usa el detector de regiones para acelerar el cálculo.",
    inApp:
      "No cambia el resultado: el área y el umbral se escalan para compensarlo.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-min-area",
    name: "Área mínima",
    group: "fuentes",
    what: "Área mínima, en píxeles, para que una región cuente como fuente extendida.",
    inApp: "Regiones más chicas se descartan antes de calcular su relevancia.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-max-area",
    name: "Área máxima",
    group: "fuentes",
    what: "Área máxima, en píxeles, de una región extendida.",
    inApp:
      "0 significa sin límite. Útil para separar la nebulosa de un fondo de estructura grande.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-closing",
    name: "Cierre",
    group: "fuentes",
    what: "Operación morfológica que rellena huecos y une bordes rotos de una región.",
    inApp:
      "Subirlo ayuda cuando la nebulosa sale cortada en pedazos. 0 desactiva.",
    where: "Inspector → Fuentes",
  },
  {
    id: "ext-opening",
    name: "Apertura",
    group: "fuentes",
    what: "Operación morfológica que corta protuberancias finas y rastro de ruido.",
    inApp:
      "Subirlo limpia la silueta pero puede dividir regiones grandes. 0 desactiva.",
    where: "Inspector → Fuentes",
  },
];
