import type { GlossaryEntry } from "./glossary-types";

export const FUENTES_ENTRIES: GlossaryEntry[] = [
  {
    id: "fuente-puntual",
    name: "Fuente puntual",
    group: "fuentes",
    what: "Objeto compacto (estrella, quasar) que en la imagen es un pico, no una mancha extendida.",
    inApp: "Se marca con un punto. Al hacer clic, sus números van a Selección.",
    where: "Visor y Inspector → Selección",
  },
  {
    id: "deteccion",
    name: "Detección de fuentes",
    group: "fuentes",
    what: "Búsqueda automática de picos sobre el fondo de la imagen.",
    inApp: "Corre con los parámetros de Fuentes y dibuja marcas sobre el FITS.",
    where: "Inspector → Fuentes",
  },
  {
    id: "fwhm",
    name: "FWHM",
    group: "fuentes",
    what: "Ancho a media altura del núcleo estelar, en píxeles.",
    inApp:
      "Valores más altos buscan estrellas más gordas o una imagen poco nítida.",
    where: "Inspector → Fuentes",
  },
  {
    id: "sigma",
    name: "Sigma",
    group: "fuentes",
    what: "Umbral de detección en RMS del fondo.",
    inApp:
      "Más alto exige picos más contrastados y suele devolver menos marcas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "snr",
    name: "SNR",
    group: "fuentes",
    what: "Relación señal / ruido del pico.",
    inApp:
      "El SNR mínimo descarta picos débiles. En Selección ves el SNR de la marca.",
    where: "Inspector → Fuentes y Selección",
  },
  {
    id: "score",
    name: "Score",
    group: "fuentes",
    what: "Puntuación de relevancia (0 a 1) que mezcla aspecto visual y forma.",
    inApp: "Filtra candidatos poco convincentes y ordena el ranking.",
    where: "Inspector → Fuentes y Selección",
  },
  {
    id: "min-distance",
    name: "Distancia mínima",
    group: "fuentes",
    what: "Separación mínima entre picos, en píxeles.",
    inApp: "Evita marcar dos veces la misma estrella.",
    where: "Inspector → Fuentes",
  },
  {
    id: "max-sources",
    name: "Máximo de fuentes",
    group: "fuentes",
    what: "Tope de fuentes a devolver, ordenadas por relevancia.",
    inApp: "0 significa sin límite. Baja el número si hay demasiadas marcas.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-weight",
    name: "Peso visual",
    group: "fuentes",
    what: "Cuánto pesa el aspecto visual frente a la morfología en el score.",
    inApp: "0 = solo forma; 1 = solo cómo se ve el parche.",
    where: "Inspector → Fuentes",
  },
  {
    id: "preset-deteccion",
    name: "Preset de detección",
    group: "fuentes",
    what: "Conjunto de umbrales con un nombre de situación (equilibrio, mucho ruido, baja resolución…).",
    inApp: "Rellena Fuentes. Si tocás un número, pasa a Personalizado.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-area-radius",
    name: "Radio visual",
    group: "fuentes",
    what: "Radio en píxeles del parche alrededor del pico para medir área, flujo y pico aparentes.",
    inApp: "Más radio mira un entorno más grande; demasiado agarra vecinos.",
    where: "Inspector → Fuentes",
  },
  {
    id: "visual-area-sigma",
    name: "Sigma visual",
    group: "fuentes",
    what: "Umbral local del parche visual, en RMS del fondo.",
    inApp: "Define qué píxeles cuentan como parte de la fuente en ese parche.",
    where: "Inspector → Fuentes",
  },
  {
    id: "rank",
    name: "Rank",
    group: "fuentes",
    what: "Orden de relevancia entre las fuentes detectadas. 1 es la más relevante.",
    inApp: "Aparece en Selección al hacer clic en una marca.",
    where: "Inspector → Selección",
  },
  {
    id: "centroide",
    name: "Centroide",
    group: "fuentes",
    what: "Posición del pico en píxeles (X, Y) sobre el HDU.",
    inApp:
      "X e Y en Selección. No son RA/Dec salvo que haya WCS (aún no se muestran ahí).",
    where: "Inspector → Selección",
  },
  {
    id: "peak",
    name: "Peak",
    group: "fuentes",
    what: "Valor de píxel en el máximo del pico.",
    inApp: "En Selección, si el detector lo calculó.",
    where: "Inspector → Selección",
  },
  {
    id: "flux",
    name: "Flux",
    group: "fuentes",
    what: "Flujo estimado de la fuente puntual (cuentas o unidad del HDU).",
    inApp: "En Selección, si el detector lo calculó.",
    where: "Inspector → Selección",
  },
];
